/* Database schema to keep the structure of entire database. */

/* Create database */
CREATE DATABASE vet_clinic ;

-- connect database 
\c vet_clinic

/* create animals' table */
 CREATE TABLE animals(
    id                 INT GENERATED BY DEFAULT AS IDENTITY,
    name               VARCHAR(100) NOT NULL,
    date_of_birth      DATE NOT NULL,
    escape_attempts    INT,
    neutered           BIT,
    weight_kg          DECIMAL) ;

   ALTER TABLE animals ADD COLUMN species VARCHAR(100);

-- create owners table 
CREATE TABLE owners(id SERIAL PRIMARY KEY, full_name VARCHAR(100), age INT);

-- create species table 
CREATE TABLE species(id SERIAL PRIMARY KEY, name VARCHAR(100));

-- MODIFY THE animals TABLE

-- Step 1: Remove the current PRIMARY KEY constraint from the "id" column
ALTER TABLE animals DROP CONSTRAINT animals_pkey;

-- Step 2: Add a new PRIMARY KEY constraint to the "id" column and set it as auto-incremented
ALTER TABLE animals ADD COLUMN id SERIAL PRIMARY KEY;

-- Step 3: Remove the "species" column
ALTER TABLE animals DROP COLUMN species;

-- Step 4: Add a new column "species_id" as a foreign key referencing the "species" table
ALTER TABLE animals ADD COLUMN species_id INT, ADD CONSTRAINT fk_species_id FOREIGN KEY (species_id) REFERENCES species(id);

-- Step 5: Add a new column "owner_id" as a foreign key referencing the "owners" table
ALTER TABLE animals ADD COLUMN owner_id INT, ADD CONSTRAINT fk_owner_id FOREIGN KEY (owner_id) REFERENCES owners(id);
