/* Database schema to keep the structure of entire database. */

/* Create database */
CREATE DATABASE vet_clinic ;

-- connect database 
\c vet_clinic

/* create table */
 CREATE TABLE animals(
    id                 INT GENERATED BY DEFAULT AS IDENTITY,
    name               VARCHAR(100) NOT NULL,
    date_of_birth      DATE NOT NULL,
    escape_attempts    INT,
    neutered           BIT,
    weight_kg          DECIMAL) ;

